markdown: redcarpet
highlighter: null
permalink: /:title

url: http://dannylee1991.github.io/
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed